applets/panelspacer: Fix unchecked access, port iterator to for(of)
Usually, child is an instance of a Loader with a `property Item applet`
where applet usually an instance of PlasmaQuick::AppletQuickItem (or
rather its subclass PlasmoidItem to be precise). However, applet could
also be an instance of a dndSpacer placeholder, which is just an Item.

Fixes the following error when dragging a piece of text over a panel:

file:///usr/local/kde/usr/share/plasma/plasmoids/org.kde.plasma.panelspacer/contents/ui/main.qml:69:
TypeError: Cannot read property 'pluginName' of undefined