libtaskmanager: add missing include for waylandtasksmodeltest
libtaskmanager/autotests/waylandtasksmodeltest.cpp:164:49: error: use of undeclared identifier 'getpid'
  164 |     lsof.setArguments({u"-p"_s, QString::number(getpid())});
      |                                                 ^