[applets/notifications] Remove leftovers of jobProgressItem
It was nuked years ago, so the id does not exist any longer, and
generated a runtime error like this:

    file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/CompactRepresentation.qml:132:
    ReferenceError: jobProgressItem is not defined

Amends da86d1e40a1d5cc2e986f3460188dbc2fb22eb3d