[applets/batterymonitor] CompactRepresentation: Fix ReferenceError
Fixes the following error:

    /usr/share/plasma/plasmoids/org.kde.plasma.battery/contents/ui/CompactRepresentation.qml:74:
    ReferenceError: batteryLabel is not defined

batteryLabel does not exist ever since commit
27ac0b760855bc5adfe85baed621bcf1efcc9194 back in 2016, so an attempt to
calculate some icon's height based on its size was bound to fail.