appiumtests: acquire bus name after self properties are set
Fixes the test error:

```
Traceback (most recent call last):
  File "/builds/plasma/powerdevil/_build/autotests/batterymonitor/tmp/appiumtests/utils/OrgFreedesktopUPower.py", line 447, in on_bus_acquired
    self.registered_event.set()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OrgFreedesktopUPower' object has no attribute 'registered_event'
```