Fix wrong class name being used in Qt6 ifdef
Should fix all these errors in CI after merging !2277

```
/var/tmp/gitlab_runner/builds/uiKp2rAD/0/plasma/plasma-workspace/shell/outputorderwatcher.cpp:259:26: error: out-of-line definition of 'nativeEventFilter' does not match any declaration in 'OutputOrderWatcher'
bool OutputOrderWatcher::nativeEventFilter(const QByteArray &eventType, void *message, qintptr *result)
                         ^~~~~~~~~~~~~~~~~
/var/tmp/gitlab_runner/builds/uiKp2rAD/0/plasma/plasma-workspace/shell/outputorderwatcher.cpp:275:25: error: use of undeclared identifier 'm_xrandrExtensionOffset'
    if (responseType == m_xrandrExtensionOffset + XCB_RANDR_NOTIFY) {
                        ^
/var/tmp/gitlab_runner/builds/uiKp2rAD/0/plasma/plasma-workspace/shell/outputorderwatcher.cpp:280:34: error: use of undeclared identifier 'm_kdeScreenAtom'
            if (property.atom == m_kdeScreenAtom) {
                                 ^
/var/tmp/gitlab_runner/builds/uiKp2rAD/0/plasma/plasma-workspace/shell/outputorderwatcher.cpp:285:17: error: use of undeclared identifier 'm_delayTimer'
                m_delayTimer->start();
                ^
```